# Generated by Django 2.2.6 on 2019-10-21 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'TV Genre',
                'verbose_name_plural': 'TV Genres',
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('media_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='media_id for TV season must follow TV[8 digit ID]', regex='^TV(\\w{8})$')])),
                ('urlPath', models.URLField()),
            ],
            options={
                'verbose_name': 'TV Show',
                'verbose_name_plural': 'TV Shows',
            },
        ),
        migrations.CreateModel(
            name='TVMetadata',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tvseries.TVShow')),
                ('poster', models.URLField()),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(default='Default TV Show Description')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'TV Metadata',
                'verbose_name_plural': 'TV Metadata',
            },
        ),
        migrations.CreateModel(
            name='TVSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvseries.TVShow')),
            ],
            options={
                'verbose_name': 'TV Season',
                'verbose_name_plural': 'TV Seasons',
            },
        ),
        migrations.CreateModel(
            name='TVGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvseries.Genre')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvseries.TVShow')),
            ],
        ),
        migrations.CreateModel(
            name='TVEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('description', models.TextField(default='Default TV Episode Description')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvseries.TVSeason')),
            ],
            options={
                'verbose_name': 'TV Episode',
                'verbose_name_plural': 'TV Episodes',
            },
        ),
        migrations.AddConstraint(
            model_name='tvseason',
            constraint=models.UniqueConstraint(fields=('show', 'number'), name='No repeating tv seasons'),
        ),
        migrations.AddConstraint(
            model_name='tvgenre',
            constraint=models.UniqueConstraint(fields=('media', 'genre'), name='No repeating tv genres'),
        ),
        migrations.AddConstraint(
            model_name='tvepisode',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='No repeating tv season episodes'),
        ),
    ]
