# Generated by Django 2.2.6 on 2019-10-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0002_auto_20191021_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvseason',
            options={},
        ),
    ]
