# Generated by Django 2.2.6 on 2019-10-21 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0003_auto_20191021_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvseason',
            options={'verbose_name': 'TV Season', 'verbose_name_plural': 'TV Seasons'},
        ),
        migrations.AlterField(
            model_name='tvseason',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
