# Generated by Django 2.2.6 on 2019-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0004_auto_20191021_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseason',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
