# Generated by Django 2.2.6 on 2019-10-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0005_auto_20191022_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisode',
            name='filename',
            field=models.CharField(default='episode1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseason',
            name='foldername',
            field=models.CharField(default='season 1', max_length=50),
            preserve_default=False,
        ),
    ]
