# Generated by Django 2.2.6 on 2019-10-21 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Movie Genre',
                'verbose_name_plural': 'Movie Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('media_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='media_id for movie must follow MV[8 digit ID]', regex='^MV(\\w{8})$')])),
                ('urlPath', models.URLField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MovieMetadata',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.Movie')),
                ('director', models.CharField(max_length=50)),
                ('poster', models.URLField()),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(default='Default Movie Description')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'Movie Metadata',
                'verbose_name_plural': 'Movie Metadata',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='moviegenre',
            constraint=models.UniqueConstraint(fields=('media', 'genre'), name='No repeating movie genres'),
        ),
    ]
